### ISSUE TITLE
Экран входа (высокий приоритет)

### ISSUE THREAD

**Issue by onionworks** [MAXBAF1/SpoonEat#33]
Проверить экран входа, возможно этот баг только на моём телефоне 

![Image](https://github.com/MAXBAF1/SpoonEat/assets/128285562/76ea3aed-e681-4a02-a7c4-55629831b312)

**Comment by lloppy** [comment]
done

![Image](https://github.com/MAXBAF1/SpoonEat/assets/67476326/0b19ea7e-7284-4a3d-8bf4-748048c96d13)
