### ISSUE TITLE
Баг с диаграммой на главном экране (низкий приоритет)

### ISSUE THREAD

**Issue by onionworks** [MAXBAF1/SpoonEat#34]
Когда нажимаешь на столбик жиров, он становится коричневым, при повторном нажатии исходный цвет возвращается

**Comment by lloppy** [comment]
done 



![Image](https://github.com/MAXBAF1/SpoonEat/assets/67476326/c12b5b54-f0a5-4fe3-8494-6af390ae0bb1)
