### ISSUE TITLE
Граммовка (высокий приоритет)

### ISSUE THREAD

**Issue by onionworks** [MAXBAF1/SpoonEat#35]
С телефона не получается указать граммовку, тк клавиатура убирается только при нажатии клавиши "назад", на нажатие которой поле ввода реагирует

**Comment by lloppy** [comment]
done 


![Image](https://github.com/MAXBAF1/SpoonEat/assets/67476326/e34078da-6382-4955-8141-96b1d912ccb8)



![Image](https://github.com/MAXBAF1/SpoonEat/assets/67476326/6eafa84c-cca6-4837-a94f-4b50bd75cc8d)
