### ISSUE TITLE
Выбор диеты (дизайн)

### ISSUE THREAD

**Issue by onionworks** [MAXBAF1/SpoonEat#37]
На экране профиля должна остаться только выбранная диета

Сделать кнопку изменить диету, окно со всеми доступными диетами и окно настройки бжу для кастомной диеты.

**Comment by lloppy** [comment]
done

![Image](https://github.com/MAXBAF1/SpoonEat/assets/67476326/c59cfa83-bb08-42cd-896b-1e873a6ab95f)

**Comment by WilgardWolf** [comment]
https://www.figma.com/file/ECFV7WPXQSdyYMIHVRe2bW/SpoonVoice(прототип)?type=design&node-id=0-1&t=QtPNiffONPAaxl7z-0
